# Yeelight C900 LED Silent Ceiling Fan
# YLFD002 / YLFD008

substitutions:
  name: yeelight-light-fancl5
  external_components_source: github://syssi/esphome-yeelight-ceiling-light@main

esphome:
  name: ${name}
  # Workaround to fix the boot loop if BLE is enabled
  # See https://github.com/syssi/esphome-yeelight-ceiling-light#known-bugs
  on_loop:
    - lambda: "vTaskDelay(10/portTICK_PERIOD_MS);"

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_mac_crc: true

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
api:
logger:

uart:
  baud_rate: 9600
  rx_pin: GPIO16
  tx_pin: GPIO17
  debug:
    direction: BOTH

fan:
  - platform: yeelight_fan_controller
    id: yeelight_ceiling_fan
    name: "${name} ceiling fan"

output:
  - platform: ledc
    pin: GPIO19
    id: output_warm
  - platform: ledc
    pin: GPIO21
    id: output_cold
  - platform: ledc
    pin: GPIO23
    id: output_nightlight

switch:
  - platform: gpio
    pin: GPIO33
    id: buzzer_beep
    on_turn_on:
      - delay: 100ms
      - switch.turn_off: buzzer_beep

light:
  - platform: monochromatic
    name: "${name} night light"
    id: night_light
    output: output_nightlight
    gamma_correct: 0
    on_turn_on:
      - light.turn_off: ceiling_light
  - platform: cwww
    name: "${name} ceiling light"
    id: ceiling_light
    cold_white: output_cold
    warm_white: output_warm
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    constant_brightness: true
    gamma_correct: 0
    on_turn_on:
      - light.turn_off: night_light

esp32_ble_tracker:
  scan_parameters:
    interval: 150ms
    window: 150ms
    duration: 1min
    active: false

xiaomi_ylyk01yl:
  mac_address: "A4:C1:38:6E:85:0B"
  last_button_pressed:
    name: "last button pressed"

  # Button             Keycode (YLYK01YL Ceiling Fan)
  # fan toggle         0
  # light toggle       1
  # wind speed         2
  # color temperature  3
  # wind mode          4
  # brightness         5
  on_press:
    - keycode: 0
      then:
        - switch.turn_on: buzzer_beep
        - fan.toggle: yeelight_ceiling_fan
    - keycode: 1
      then:
        - switch.turn_on: buzzer_beep
        - light.toggle: ceiling_light
    - keycode: 2
      then:
        - switch.turn_on: buzzer_beep
        - logger.log: "Button wind speed pressed"
    - keycode: 3
      then:
        - switch.turn_on: buzzer_beep
        - logger.log: "Button color temperature pressed"
    - keycode: 4
      then:
        - switch.turn_on: buzzer_beep
        - logger.log: "Button wind mode pressed"
    - keycode: 5
      then:
        - switch.turn_on: buzzer_beep
        - logger.log: "Button brightness pressed"

    # Trigger on any keycode
    - then:
        - logger.log:
            format: 'Button with keycode %d pressed'
            args: ['int(keycode)']

  on_long_press:
    # Trigger on any keycode
    - then:
        - logger.log:
            format: 'Button with keycode %d long pressed'
            args: ['int(keycode)']
